/** 调试面板字段注册表：slide → 参数组 → 源文件引用 */

import { FONT, MS, PX, PCT, PCT0, SCALE, SEC } from "../motion-tuning/schema/fieldPresets.js";
import { COVER_TIMELINES, SUMMARY_TIMELINES, buildDfsTimelines } from "./animTimeline.js";
import { DFS_STEPS } from "./buildDfsSteps.js";
import { mergeLayoutBase, layoutBaseFieldEntries } from "./layoutBase.js";

export { cssVarUnit, formatCssVarValue, parseCssVarNumber } from "../motion-tuning/schema/cssVar.js";

export const SLIDE_TUNING = {
  cover: {
    label: "封面",
    timelines: COVER_TIMELINES,
    groups: [
      {
        id: "cover-deck-transition",
        title: "幻灯片切换",
        role: "motion",
        block: "DECK_TRANSITION",
        source: { file: "src/maxDepth/MaxDepthPresentation.jsx", lines: "81-87" },
        fields: {
          duration: SEC("切换时长 (s)"),
          initialY: PX("进入起始 Y"),
          exitY: PX("退出终点 Y"),
          scale: SCALE("缩放"),
        },
      },
      {
        id: "cover-motion",
        title: "封面 Motion",
        role: "motion",
        layoutSlug: "cover-difficulty",
        layoutKind: "css",
        layoutBlock: "DECK_CSS_VARS",
        layoutFields: layoutBaseFieldEntries("cover-difficulty"),
        textBlock: "DECK_TEXT",
        textFields: { coverDifficulty: "难度标签" },
        block: "COVER_MOTION",
        source: { file: "src/maxDepth/components/CoverSlide.jsx", lines: "10-39" },
        fields: {
          titleInitialY: PX("标题起始 Y"),
          titleDuration: SEC("标题时长 (s)"),
          difficultyInitialY: PX("难度起始 Y"),
          difficultyInitialScale: SCALE("难度起始缩放"),
          difficultyHiddenY: PX("难度隐藏 Y"),
          difficultyHiddenScale: SCALE("难度隐藏缩放"),
          difficultySlotMaxHeight: PX("难度槽高度"),
          difficultySlotPadding: PX("难度槽内边距"),
          difficultySlotDuration: SEC("难度槽时长 (s)"),
          difficultyDuration: SEC("难度时长 (s)"),
          titleShrinkScale: SCALE("标题微缩比例"),
          titleShrinkY: PX("标题微缩 Y"),
          titleShrinkDuration: SEC("标题微缩时长 (s)"),
        },
      },
      {
        id: "cover-teaser-left",
        title: "封面预告 · 自顶向下",
        role: "layout",
        layoutSlug: "cover-teaser-left",
        kind: "css",
        block: "DECK_CSS_VARS",
        textBlock: "DECK_TEXT",
        textFields: { summaryTopPanelTitle: "Panel 标题" },
        source: { file: "src/maxDepth/components/CoverApproachTeaser.jsx", lines: "82-97" },
        fields: mergeLayoutBase(
          {
            "--md-cover-teaser-bottom": PCT0("预告区距底 (%)"),
            "--md-cover-teaser-gap": PX("双 Panel 间距 (px)"),
            "--md-cover-teaser-title-size": FONT("Panel 标题字号 (px)"),
            "--md-cover-teaser-left-shift-x": PX("水平偏移 (px)"),
            "--md-cover-teaser-left-shift-y": PX("垂直偏移 (px)"),
          },
          "cover-teaser-left",
        ),
        manip: {
          drag: {
            type: "css",
            keys: ["--md-cover-teaser-left-shift-x", "--md-cover-teaser-left-shift-y"],
          },
          scale: { type: "css", key: "--md-cover-teaser-left-layout-size", min: 0.5, max: 2 },
        },
        hint: "需节拍 2 才可见；Ctrl+拖动位移，Ctrl+滚轮缩放",
      },
      {
        id: "cover-teaser-right",
        title: "封面预告 · 自底向上",
        role: "layout",
        layoutSlug: "cover-teaser-right",
        kind: "css",
        block: "DECK_CSS_VARS",
        textBlock: "DECK_TEXT",
        textFields: { summaryBottomPanelTitle: "Panel 标题" },
        source: { file: "src/maxDepth/components/CoverApproachTeaser.jsx", lines: "114-128" },
        fields: mergeLayoutBase(
          {
            "--md-cover-teaser-right-shift-x": PX("水平偏移 (px)"),
            "--md-cover-teaser-right-shift-y": PX("垂直偏移 (px)"),
          },
          "cover-teaser-right",
        ),
        manip: {
          drag: {
            type: "css",
            keys: ["--md-cover-teaser-right-shift-x", "--md-cover-teaser-right-shift-y"],
          },
          scale: { type: "css", key: "--md-cover-teaser-right-layout-size", min: 0.5, max: 2 },
        },
        hint: "需节拍 2 才可见；Ctrl+拖动位移，Ctrl+滚轮缩放",
      },
      {
        id: "cover-teaser",
        title: "封面预告 · 动画",
        role: "motion",
        block: "COVER_TEASER_MOTION",
        source: { file: "src/maxDepth/components/CoverApproachTeaser.jsx", lines: "21-68" },
        fields: {
          panelEnterY: PX("Panel 起始 Y"),
          panelDuration: SEC("Panel 时长 (s)"),
          panelStagger: SEC("右 Panel 延迟 (s)"),
          loopInterval: MS("左树 pulse 周期 (ms)"),
          flashInterval: MS("右示意 flash 周期 (ms)"),
        },
      },
      {
        id: "cover-fonts",
        title: "封面字号 / 间距",
        role: "layout",
        layoutSlug: "cover-title",
        textBlock: "DECK_TEXT",
        textFields: {
          coverLeetcode: "LeetCode 编号",
          coverTitle: "主标题",
        },
        block: "DECK_CSS_VARS",
        kind: "css",
        source: { file: "src/maxDepth/animConfig.js", lines: "DECK_CSS_VARS" },
        fields: mergeLayoutBase(
          {
            "--md-cover-title-size": FONT("主标题字号 (px)"),
            "--md-cover-leetcode-size": FONT("LeetCode 字号 (px)"),
            "--md-cover-difficulty-size": FONT("难度字号 (px)"),
            "--md-cover-difficulty-gap": PX("难度与标题间距 (px)"),
            "--md-cover-stage-offset-y": PX("封面整体上移 (px)"),
          },
          "cover-title",
        ),
        hint: "「难度与标题间距」需将进度条调到节拍 2（难度标签出现后）才可见",
        manip: {
          drag: { type: "css", keys: ["--md-cover-stage-offset-y"], axes: ["y"] },
        },
      },
    ],
  },
  summary: {
    label: "做法总结",
    timelines: SUMMARY_TIMELINES,
    groups: [
      {
        id: "summary-timing",
        title: "时序 (ms)",
        role: "timing",
        block: "SUMMARY_TIMING",
        source: { file: "src/maxDepth/components/SummarySlide.jsx", lines: "51-93" },
        fields: {
          panelFlash: MS("Panel 闪烁"),
          edgePulseFirst: MS("边 pulse ①"),
          edgePulseSecond: MS("边 pulse ②"),
          flashLeft: MS("左子树闪烁"),
          annoBlue: MS("蓝箭头等待"),
          flashRight: MS("右子树闪烁"),
          badgePopDelay: MS("Badge 延迟"),
          badgeFinalDelay: MS("最终 Badge 延迟"),
        },
      },
      {
        id: "summary-tree-motion",
        title: "自顶向下树 / 边 pulse",
        role: "motion",
        layoutSlug: "summary-tree",
        layoutKind: "css",
        layoutBlock: "DECK_CSS_VARS",
        layoutFields: layoutBaseFieldEntries("summary-tree"),
        block: "SUMMARY_TREE_MOTION",
        source: { file: "src/maxDepth/components/TreeSvg.jsx", lines: "49-59" },
        fields: {
          edgePulseDuration: SEC("边 pulse 时长 (s)"),
        },
        hint: "点击上方 md-tree-svg 调节；与自底向上示意独立",
      },
      {
        id: "summary-schematic-motion",
        title: "自底向上示意 / 箭头",
        role: "motion",
        layoutSlug: "summary-schematic",
        layoutKind: "css",
        layoutBlock: "DECK_CSS_VARS",
        layoutFields: layoutBaseFieldEntries("summary-schematic"),
        textBlock: "DECK_TEXT",
        textFields: {
          schematicLeftCaption: "左子树标注",
          schematicRightCaption: "右子树标注",
        },
        block: "SUMMARY_SCHEMATIC_MOTION",
        source: { file: "src/maxDepth/components/SubtreeSchematic.jsx", lines: "46-58" },
        fields: {
          annoBlueDuration: SEC("蓝箭头绘制时长 (s)"),
          annoGoldDuration: SEC("金箭头绘制时长 (s)"),
        },
        hint: "点击下方 md-schematic-svg 调节；控制 pathLength 绘制速度",
      },
      {
        id: "summary-badge-motion",
        title: "Summary Badge pop",
        role: "motion",
        block: "SUMMARY_BADGE_MOTION",
        source: { file: "src/maxDepth/components/SummarySlide.jsx", lines: "SummaryBadgeAnchor" },
        fields: {
          badgeInitialScale: SCALE("Badge 起始缩放"),
        },
      },
      {
        id: "summary-panel-enter",
        title: "Panel 入场位置",
        role: "layout",
        layoutSlug: "summary-panel-top",
        textBlock: "DECK_TEXT",
        textFields: { summaryTopPanelTitle: "Panel 标题" },
        block: "DECK_CSS_VARS",
        kind: "css",
        source: { file: "src/maxDepth/animConfig.js", lines: "DECK_CSS_VARS" },
        fields: mergeLayoutBase(
          {
            "--md-summary-top-enter-y": PX("上 Panel 入场 Y (px)"),
            "--md-summary-top-enter-scale": SCALE("上 Panel 入场缩放"),
            "--md-summary-top-step1-x": PX("Step1 X 偏移 (px)"),
            "--md-summary-bottom-enter-x": PX("下 Panel 入场 X (px)"),
            "--md-summary-bottom-enter-y": PX("下 Panel 入场 Y (px)"),
          },
          "summary-panel-top",
        ),
        manipByRole: {
          top: {
            scale: { type: "css", key: "--md-summary-top-enter-scale", min: 0.5, max: 2 },
            drag: {
              type: "css",
              keys: ["--md-summary-top-step1-x", "--md-summary-top-enter-y"],
            },
          },
          bottom: {
            drag: {
              type: "css",
              keys: ["--md-summary-bottom-enter-x", "--md-summary-bottom-enter-y"],
            },
          },
        },
      },
      {
        id: "summary-panel-final",
        title: "Panel 落定位置（Step≥1 可见）",
        role: "layout",
        layoutSlug: "summary-panel-bottom",
        textBlock: "DECK_TEXT",
        textFields: { summaryBottomPanelTitle: "Panel 标题" },
        block: "DECK_CSS_VARS",
        kind: "css",
        source: { file: "src/maxDepth/animConfig.js", lines: "DECK_CSS_VARS" },
        fields: mergeLayoutBase(
          {
            "--md-summary-top-step1-y": PX("上 Panel Step1 Y (px)"),
            "--md-summary-top-final-x": PX("上 Panel 最终 X (px)"),
            "--md-summary-top-final-y": PX("上 Panel 最终 Y (px)"),
            "--md-summary-bottom-final-x": PX("下 Panel 最终 X (px)"),
            "--md-summary-bottom-final-y": PX("下 Panel 最终 Y (px)"),
            "--md-panel-title-size": FONT("Panel 标题字号 (px)"),
          },
          "summary-panel-bottom",
        ),
        manipByRole: {
          top: {
            drag: {
              type: "css",
              keys: ["--md-summary-top-final-x", "--md-summary-top-final-y"],
            },
          },
          bottom: {
            drag: {
              type: "css",
              keys: ["--md-summary-bottom-final-x", "--md-summary-bottom-final-y"],
            },
          },
        },
      },
      {
        id: "summary-badge-green",
        title: "绿色 Badge（最大深度 = 3）",
        role: "layout",
        layoutSlug: "summary-badge-green",
        textBlock: "DECK_TEXT",
        textFields: { summaryTopBadge: "Badge 文案" },
        block: "DECK_CSS_VARS",
        kind: "css",
        source: { file: "src/maxDepth/animConfig.js", lines: "DECK_CSS_VARS" },
        fields: mergeLayoutBase(
          {
            "--md-tree-badge-top": PX("垂直位置 (px，可负)"),
            "--md-tree-badge-shift-x": PX("水平微调 (px)"),
            "--md-tree-badge-shift-y": PX("垂直微调 (px，可负)"),
            "--md-tree-badge-font-size": FONT("字号 (px)"),
          },
          "summary-badge-green",
        ),
        hint: "节拍 2 出现绿色胶囊；定位在 .md-tree-badge-anchor，负 top/shift-y 往上移",
        manip: {
          drag: {
            type: "css",
            keys: ["--md-tree-badge-shift-x", "--md-tree-badge-shift-y"],
          },
        },
      },
      {
        id: "summary-badge-gold",
        title: "金色 Badge（底部 Panel）",
        role: "layout",
        layoutSlug: "summary-badge-gold",
        textBlock: "DECK_TEXT",
        textFields: { summaryBottomBadge: "Badge 文案" },
        block: "DECK_CSS_VARS",
        kind: "css",
        source: { file: "src/maxDepth/animConfig.js", lines: "DECK_CSS_VARS" },
        fields: mergeLayoutBase(
          {
            "--md-tree-badge-gold-top": PX("垂直位置 (px，可负)"),
            "--md-tree-badge-gold-shift-x": PX("水平微调 (px)"),
            "--md-tree-badge-gold-shift-y": PX("垂直微调 (px，可负)"),
            "--md-tree-badge-gold-font-size": FONT("字号 (px)"),
          },
          "summary-badge-gold",
        ),
        hint: "节拍 3 出现金色胶囊；负值往上移，避开示意树",
        manip: {
          drag: {
            type: "css",
            keys: ["--md-tree-badge-gold-shift-x", "--md-tree-badge-gold-shift-y"],
          },
        },
      },
      {
        id: "summary-utils",
        title: "工具动画",
        role: "motion",
        block: "PLAYBACK_UTILS",
        source: { file: "src/maxDepth/useDfsPlayback.js", lines: "137-146" },
        fields: {
          popBadgeDuration: SEC("Badge pop 时长 (s)"),
          popBadgeScaleMid: SCALE("Badge pop 峰值缩放"),
          panelFlash: MS("Panel flash (ms)"),
        },
      },
    ],
  },
  dfs: {
    label: "DFS 演示",
    timelines: buildDfsTimelines(DFS_STEPS),
    groups: [
      {
        id: "dfs-timing",
        title: "DFS 时序 (ms)",
        role: "timing",
        block: "DFS_TIMING",
        source: { file: "src/maxDepth/useDfsPlayback.js", lines: "60-99" },
        fields: {
          enterNode: MS("进入节点"),
          enterEdge: MS("进入边"),
          leafFlashLoop: MS("叶子闪烁单圈"),
          leaveEdge: MS("离开边"),
        },
      },
      {
        id: "dfs-motion",
        title: "DFS Motion",
        role: "motion",
        block: "DFS_MOTION",
        source: { file: "src/maxDepth/components/DfsSlide.jsx", lines: "27-40" },
        fields: {
          depthCardEnterY: PX("深度卡进入 Y"),
          depthCardExitY: PX("深度卡退出 Y"),
          depthCardScale: SCALE("深度卡起始缩放"),
          depthCardDuration: SEC("深度卡时长 (s)"),
          depthValueScale: SCALE("数值 pulse 缩放"),
          depthValueDuration: SEC("数值 pulse 时长 (s)"),
          nodePulseScale: SCALE("节点 pulse 缩放"),
          nodePulseDuration: SEC("节点 pulse 时长 (s)"),
          nodeFlashDuration: SEC("节点 flash 时长 (s)"),
          edgePulseDuration: SEC("边 pulse 时长 (s)"),
          pathBadgeInitialScale: SCALE("深度标起始缩放"),
          pathBadgePopDuration: SEC("深度标 pop 时长 (s)"),
          pathBadgePopScaleMid: SCALE("深度标 pop 峰值"),
        },
      },
      {
        id: "dfs-badge-layout",
        title: "节点深度标位置（按节点）",
        role: "layout",
        block: "DFS_BADGE_LAYOUT",
        kind: "array",
        source: { file: "src/maxDepth/animConfig.js", lines: "DFS_BADGE_LAYOUT" },
        fields: {
          layoutLeft: PCT0("水平位置 (%)"),
          layoutSize: SCALE("大小 (缩放)"),
          shiftX: PX("X 微调 (px)"),
          shiftY: PX("Y 微调 (px，负=上)"),
        },
        hint: "展开对应节点卡片调节；负 Y 往上移，避开节点圆",
        manip: {
          drag: { type: "array", keys: ["shiftX", "shiftY"] },
        },
      },
      {
        id: "dfs-depth-card",
        title: "深度卡布局",
        role: "layout",
        layoutSlug: "dfs-depth-card",
        textBlock: "DECK_TEXT",
        textFields: { dfsDepthLabel: "卡片标签" },
        block: "DECK_CSS_VARS",
        kind: "css",
        source: { file: "src/maxDepth/animConfig.js", lines: "DECK_CSS_VARS" },
        fields: mergeLayoutBase(
          {
            "--md-dfs-depth-card-top": PCT("垂直位置 (%)"),
            "--md-dfs-depth-card-left": PCT0("水平位置 (%)"),
            "--md-dfs-depth-card-shift-x": PX("水平微调 (px)"),
            "--md-dfs-depth-card-shift-y": PX("垂直微调 (px)"),
            "--md-dfs-depth-value-size": FONT("深度数值字号 (px)"),
          },
          "dfs-depth-card",
        ),
        hint: "需调到出现深度卡的节拍；left + shift-x 控制水平位置",
        manip: {
          drag: {
            type: "css",
            keys: ["--md-dfs-depth-card-shift-x", "--md-dfs-depth-card-shift-y"],
          },
        },
      },
      {
        id: "dfs-tree",
        title: "DFS 树整体",
        role: "layout",
        layoutSlug: "dfs-tree",
        block: "DECK_CSS_VARS",
        kind: "css",
        source: { file: "src/maxDepth/animConfig.js", lines: "DECK_CSS_VARS" },
        fields: mergeLayoutBase(
          {
            "--md-dfs-tree-scale": SCALE("树缩放"),
            "--md-dfs-tree-shift-x": PX("树水平位移 (px)"),
            "--md-dfs-tree-shift-y": PX("树垂直位移 (px)"),
          },
          "dfs-tree",
        ),
        hint: "缩放整棵 SVG，节点与深度小标一起缩放，相对位置不变",
        manip: {
          scale: { type: "css", key: "--md-dfs-tree-scale", min: 0.3, max: 5 },
          drag: {
            type: "css",
            keys: ["--md-dfs-tree-shift-x", "--md-dfs-tree-shift-y"],
          },
        },
      },
    ],
  },
};
